export const BARRIOS_CUCUTA = [
  'Atalaya',
  'Belén',
  'Blanco',
  'Caobos',
  'Centro',
  'Chapinero',
  'Cundinamarca',
  'El Contento',
  'El Llano',
  'El Pórtico',
  'El Salado',
  'Escobal',
  'Gramalote',
  'Juan Atalaya',
  'La Ceiba',
  'La Ermita',
  'La Esperanza',
  'La Floresta',
  'La Garita',
  'La Libertad',
  'La Merced',
  'La Niza',
  'La Parada',
  'Las Américas',
  'Las Colinas',
  'Las Delicias',
  'Los Alpes',
  'Motilones',
  'Nueva Granada',
  'Nuevo Horizonte',
  'Palo Gordo',
  'Patios',
  'Porcelana',
  'Prados del Norte',
  'Quinta Orientales',
  'Ricaurte',
  'Samaria',
  'San Eduardo',
  'San Luis',
  'San Miguel',
  'Santa Lucía',
  'Sevilla',
  'Simón Bolívar',
  'Tasajero',
  'Torcoroma',
  'Trigal del Norte',
  'Villa del Rosario',
  'Villanueva',
  'Wayuu',
  'Otro',
]
